media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: source/_posts
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: pics
    label: Pics
    type: collection
    path: source/images
    fields:
      - name: title
        type: string